document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'/>");
document.writeln("	<meta charset=\'utf-8\'>");
document.writeln("<head>");
document.writeln("	<style type=\'text/css\'>");
document.writeln("	.gg11 p{");
/*document.writeln("		background-color: yellow;");*/
document.writeln("		font-weight: bold;");
document.writeln("		margin: 0px;");
document.writeln("		font-size: 15px;");
document.writeln("		color: red;");
document.writeln("	}");
document.writeln("	.gg3{");
document.writeln("		font-size: 20px;");
document.writeln("	}");
document.writeln("		@media screen and (max-width:600px){");
document.writeln("        .gg11 p{");
document.writeln("        	font-size: 15px;");
document.writeln("        }");
document.writeln("        .gg11 .gg3{");
document.writeln("		font-size: 10px;");
document.writeln("	}");
document.writeln("		 }");
document.writeln("		");
document.writeln("	</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("	<div class=\'gg11\'>");
document.writeln("      <a class=\'czzc\' href=\'http://www.00959a.com/\'  target=\'_blank\' style=\'text-decoration: none;\'>");
document.writeln("      <p>版主郑重声明:</p>");
document.writeln("      <p>\&nbsp\&nbsp\&nbsp\&nbsp\&nbsp\&nbsp《葡京彩票》已在本心水论坛先行支付5年广告费用和1亿信誉押金,还未进行充值的朋友可以放心大胆的充值投注,如有无故拖欠或未支付客户款项的,请添加版主QQ:1005990723。一经查明情况属实的本站将启用押金先行赔付客户资金,双重安全保障大家尽可放心充值投注。</p>");
document.writeln("     </a>");
document.writeln("      <a class=\'czzc\' href=\'http://220606.com:888/\'  target=\'_blank\' style=\'text-decoration: none;\'>");
document.writeln("      <p align=\'center\' style=\'background-color: #000\' class=\'gg3\'>");
document.writeln("      	<img src=\'/images/88.gif\' style=\'width: 100%;height: auto\'></p>");
document.writeln("     ");
document.writeln("     </a>");
document.writeln("     </div>");
document.writeln("</body>");
document.writeln("</html>");